# Site settings
title: Amirhossein Alimohammadi  # Your name or the title for your website
description: >-  # A brief description of your website
  Amir's personal webpage.

url: "alimohammadiamirhossein.github.io"  # Your website URL
twitter_username: amirhossein_alm  # Your Twitter username
github_username: alimohammadiamirhossein  # Your GitHub username

# Build settings
theme: minima
plugins:
  - jekyll-feed
